### ISSUE TITLE
Добавить преобразование для примитивов

### ISSUE THREAD

**Issue by ahiipsa** [koorchik/LIVR#11]
Было бы удобно иметь базовом функционале преобразование для примитивов (integer, boolean, string, ...).
В моем кейсе, прилетают данные в POST запросе в виде строки [Пример формы](http://jsfiddle.net/ahiipsa/zwreeyt1/)
Приходиться дополнительно после валидации делать `parseInt(value, 10)`

**Comment by SDSWanderer** [comment]
Мне кажется сложно будет обеспечить одинаковое поведение для всех реализаций. Например, для perl преобразование из строки "10" в число 10 вообще не имеет смысла - это одно и тоже.

**Comment by koorchik** [comment]
Валидировать типы сложно, например, не до конца ясно, как должны работать правила в Perl. В целом, например, для "number" можно просто смотреть, что строка выглядит как число, но тесты спецификации будут несовместимы.

Относительно преобразования, то тут проще. Например, для правила "to_number"  в Perl можно тоже преобразовать строку в число, для Perl типы значения не имеют, но при генерации JSON  разница будет.

Проблема с типами для JS явно актуальна, но стоит ее решать на уровне спеки или на уровне JS конкретной реализации это еще вопрос.

@SDSWanderer  актуальна ли эта проблема для PHP?

**Comment by koorchik** [comment]
@asholok актуальна ли эта проблема для Python? Какие предложения по работе с типами?

**Comment by asholok** [comment]
@koorchik  В Python существует утиная типизация - то есть стратегия поведения с обьектом зависит от самого обьекта. Но в нашем случае все зависит от установки правил валидации, так что при вероятности попадании в правило валидации данньіх не соответствующих типов я перестраховуюсь и юзаю врапьі int(val), bool(val), str(val).

**Comment by koorchik** [comment]
Ясно. В целом, так делает и js реализация.  Если говорим "min_number", то перед проверкой валидатор приведет все к строке, но на выход получим оригинальное значение. А затем уже после валидации приходится преобразовывать строки в числа (или сразу или в местах их использования). Это актуально для JS, поскольку там некоторые операторы полиморфные. В Perl этого делать не нужно, поскольку все операторы мономорфные. В Python полиморфные операторы + строгая типизация, то есть будут вылетать исключение. Кроме того все усугубляется тем, что есть  int-ы и float-ы, как они между собой я не в курсе, но думаю есть какие-то нюансы и не всегда хорошо будет приводить любое число к float. В JS же проблемы нет (да и внутренне все и так 64bit float).

Следующие кейс - это использование LIVR не для API а для валидации конфигов, там конечно лучше явно ограничивать разрешенный тип, а не преобразовывать.

**Comment by SDSWanderer** [comment]
Для PHP реализации в целом актуальны эти же проблемы. Функции которые работают со строками при передачи в качестве аргумента числа бросают исключение.

**Comment by koorchik** [comment]
It's time to solve the issue :). @pterolex, @asholok, @maktwin, @SDSWanderer, @Prots, @WebbyLab, @YanaSavchenko, @antonfin

It can be most significant change in v0.5. We have several ways to deal with this. The first one is to restrict types:
1) But if we will require number 1 instead of string "1"  it will break a lot of code
2) In Perl there is no difference between 1 and "1"
3) Moreover, in this case we should have different test suites for different languages.
So, this approach will not work well.

The second option is to make types coercing in numeric rules. So, positive_integer will coerce string to number or int depending on the implementation. This looks more reasonable because if someone says "positive_integer" then he expects to receive positive_integer after validation.

What about the test suite? The test suite is stored in JSON format, therefore we can rely only on types that are supported by JSON. So, if we have input ```{field: "1"}```, rules ```{field: 'positive_integer'}``` then the output will be ```{field: 1}```.
1) JavaScript will coerce "1" to 1. And the test will pass.
2) Perl will do nothing. And the test will pass.
3) Python should coerce "1" to Int. If python's json parser will treat all int-looking numbers as Integers then it will work. But if it parses them as floats, then "positive_integer" rule should coerce to Floats too to make the test pass. @asholok, could you help with this?
4) Ruby??? @maktwin, will it work with Ruby?
5) Erlang??? @Prots, will it work with Erlang?
6) PHP??? @antonfin, @SDSWanderer  will it work with PHP?

**Comment by Prots** [comment]
Yes, it will work in Erlang, but after few fixes in code. Now for verification {field: "1"}, rules {field: 'positive_integer'} I use type conversion binary -> integer , but return input value. So for solving this problem I need return converted value, that's it.

**Comment by koorchik** [comment]
More examples here #22. Moreover, there is one more question. How to deal with numbers when a string is expected? Convert to string? 

And one issue is equality. Should it be strict or not? And should we do any type coercing of result?  For example, for "one_of" or "equal" (#6) rules. One of the options is to treat rules as expectations. 
I mean if we have input ```{field: 1}``` and rules ```{field: {one_of: ['1.0000'] } }``` then we should make relaxed comparison of 1 and  '1.0000', they are equal. And we should return not coerced value but **value from the rule**, it will be '1.0000'. This approach will work because developer expects that the value will be one_of: ['1.0000']

What do you think? Any ideas?

**Comment by koorchik** [comment]
Adding @siavolt to the discussion

**Comment by koorchik** [comment]
Have added description to the spec and have updated test suite. Will be available soon
